apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: tutorial-appset
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - env: dev
          - env: prod
  template:
    metadata:
      name: "apps-{{env}}"
      namespace: argocd
    spec:
      project: tutorial-app-of-apps
      source:
        repoURL: git@github.com:kagodarog/k8s.git
        targetRevision: HEAD
        path: envs/{{env}}
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
        syncOptions:
          - Validate=true
          - CreateNamespace=false
          - PrunePropagationPolicy=foreground
          - PruneLast=true