apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - project.yaml
  - applicationset.yaml
  - argocd-notifications-cm.yaml
  - argocd-notifications-secret.yaml # This is the secret that contains the GitHub token. You need to provide your own file. This is currently gitignored
  - repo-secret.yaml  # This is the secret that contains the GitHub token. You need to provide your own file. This is currently gitignored


#increase eks instance pod numbers
# kubectl set env daemonset aws-node -n kube-system ENABLE_PREFIX_DELEGATION=true
# kubectl set env ds aws-node -n kube-system WARM_IP_TARGET=1
# kubectl set env ds aws-node -n kube-system MINIMUM_IP_TARGET=1